{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: 'Logger' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x721a8f5e4090>\ninitialize_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4e1a6ba9e38be83b943437268023ce3d\")>\nlogger_creation = <Logger conftest (DEBUG)>\n\n    def test_login(self, initialize_driver,logger_creation):\n      home_page = HomePage(initialize_driver)\n>     logger = logger_creation()\nE     TypeError: 'Logger' object is not callable\n\ntests/test_login.py:18: TypeError"}, "start": 1732029576157, "stop": 1732029576160, "uuid": "aef1cd0a-beaa-4fac-93b3-223dffd0a32c", "historyId": "2116f0ad00ab1de0effc54f114dd9496", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "aelita-hp-pavilion"}, {"name": "thread", "value": "49569-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}