{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: 'Logger' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x764f53f04550>\ninitialize_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"227026e0b2746803b8e7d2c5c681a643\")>\nlogger_creation = <Logger conftest (DEBUG)>\n\n    def test_login(self, initialize_driver, logger_creation):\n      home_page = HomePage(initialize_driver)\n>     log = logger_creation()\nE     TypeError: 'Logger' object is not callable\n\ntests/test_login.py:18: TypeError"}, "start": 1732139115002, "stop": 1732139115003, "uuid": "2e90d9f2-0a06-431b-ae18-aa952e8b119e", "historyId": "2116f0ad00ab1de0effc54f114dd9496", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "aelita-hp-pavilion"}, {"name": "thread", "value": "75510-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}