{"uuid": "d2f03657-0c8c-4ef6-8ab8-fad3b027ab93", "children": ["de92b2a1-d1e4-4338-abc7-239aa41b736d"], "befores": [{"name": "initialize_driver", "status": "passed", "start": 1731596978557, "stop": 1731596981500}], "afters": [{"name": "initialize_driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=130.0.6723.116)\nStacktrace:\n#0 0x5c196071a6da <unknown>\n#1 0x5c196022ef80 <unknown>\n#2 0x5c19602146ee <unknown>\n#3 0x5c1960215b0f <unknown>\n#4 0x5c196022f4d6 <unknown>\n#5 0x5c1960204e24 <unknown>\n#6 0x5c19602ae77b <unknown>\n#7 0x5c196029fb78 <unknown>\n#8 0x5c196026e72e <unknown>\n#9 0x5c196026f79e <unknown>\n#10 0x5c19606e5f1b <unknown>\n#11 0x5c19606e9eb8 <unknown>\n#12 0x5c19606d342c <unknown>\n#13 0x5c19606eaa37 <unknown>\n#14 0x5c19606b7fef <unknown>\n#15 0x5c1960708ad8 <unknown>\n#16 0x5c1960708ca0 <unknown>\n#17 0x5c1960719556 <unknown>\n#18 0x7700d5297b5a <unknown>\n\n", "trace": "  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/home/aelita/Projects/some/git_project/online_shop/conftest.py\", line 13, in initialize_driver\n    driver.close()\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 491, in close\n    self.execute(Command.CLOSE)\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1731596986764, "stop": 1731596986774}], "start": 1731596978557, "stop": 1731596986775}