[33mWARNING [0m tests.test_login:test_login.py:29 message1
[1m[31mERROR   [0m tests.test_login:test_login.py:30 message2